=== Darius-Cos/Full_Stack_Project_2/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume, prenume, varsta, adresa?, informatii-cv?)>
<!ATTLIST persoana id ID #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT informatii-cv (studii?, experienta?)>
<!ELEMENT studii (#PCDATA)>
<!ELEMENT experienta (#PCDATA)>

=== Darius-Cos/Full_Stack_Project_2/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="p1">
        <nume>Costache</nume>
        <prenume>Darius</prenume>
        <varsta>21</varsta>
        <adresa>
            <strada>Strada Bradului</strada>
            <numar>10</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
    </persoana>
</persoane>

=== Darius-Cos/Full_Stack_Project_2/continut/resurse/persoane1.2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
  <persoana id="p1">

    <nume>Grigore</nume>
    <prenume>Matei</prenume>
    <varsta>23</varsta>
    <adresa>
      <strada>Strada Marii</strada>
      <numar>56</numar>
      <localitate>Iași</localitate>
      <judet>Iași</judet>
      <tara>Romania</tara>
    </adresa>
    <informatii-cv>
      <studii>Universitatea Tehnică din Iași</studii>
      <experienta>Student</experienta>
    </informatii-cv>
  </persoana>
  <persoana id="p2">

    <nume>Mircea</nume>
    <prenume>Noe</prenume>
    <varsta>35</varsta>
    <adresa>
      <strada>Strada Unirii</strada>
      <numar>6</numar>
      <localitate>București</localitate>
      <judet>București</judet>
      <tara>Romania</tara>
    </adresa>
    <informatii-cv>
      <studii>Universitatea București</studii>
      <experienta>Engineer</experienta>
    </informatii-cv>
  </persoana>
  <persoana id="p3">
    <nume>Maria</nume>
    <prenume>Cristina</prenume>
    <varsta>28</varsta>
    <adresa>
      <strada>Strada Victoriei</strada>
      <numar>45</numar>
      <localitate>Cluj-Napoca</localitate>
      <judet>Cluj</judet>
      <tara>Romania</tara>
    </adresa>
    <informatii-cv>
      <studii>Universitatea Babeș-Bolyai</studii>
      <experienta>Doctorant</experienta>
    </informatii-cv>
  </persoana>
</persoane>
